package service

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	pb "github.com/brotherlogic/sale-description-generator/api/gen/v1"
)

const (
	defaultLocalEndpoint = "http://192.168.68.112:11434/v1"
	defaultLocalModel    = "deepseek-coder-v2:latest"
)

// LocalGenerator generates descriptions using a local Ollama OpenAI-compatible endpoint.
type LocalGenerator struct {
	endpoint   string
	model      string
	httpClient *http.Client
}

// NewLocalGenerator creates a new LocalGenerator.
func NewLocalGenerator(endpoint, model string) *LocalGenerator {
	if endpoint == "" {
		endpoint = os.Getenv("OLLAMA_ENDPOINT")
	}
	if endpoint == "" {
		endpoint = defaultLocalEndpoint
	}
	endpoint = strings.TrimSuffix(endpoint, "/")

	if model == "" {
		model = os.Getenv("OLLAMA_MODEL")
	}
	if model == "" {
		model = defaultLocalModel
	}

	return &LocalGenerator{
		endpoint: endpoint,
		model:    model,
		httpClient: &http.Client{
			Timeout: 60 * time.Second,
		},
	}
}

type chatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type chatCompletionRequest struct {
	Model       string        `json:"model"`
	Messages    []chatMessage `json:"messages"`
	Temperature float64       `json:"temperature,omitempty"`
}

type chatCompletionResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// Generate produces a sale description using the local Ollama LLM.
func (l *LocalGenerator) Generate(ctx context.Context, req *pb.GenerateDescriptionRequest) (string, error) {
	prompt := ConstructPrompt(req)

	bodyReq := chatCompletionRequest{
		Model: l.model,
		Messages: []chatMessage{
			{
				Role:    "user",
				Content: prompt,
			},
		},
	}

	payload, err := json.Marshal(bodyReq)
	if err != nil {
		return "", fmt.Errorf("failed to marshal chat request: %w", err)
	}

	url := fmt.Sprintf("%s/chat/completions", l.endpoint)
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(payload))
	if err != nil {
		return "", fmt.Errorf("failed to create http request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	httpResp, err := l.httpClient.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("local model request failed: %w", err)
	}
	defer httpResp.Body.Close()

	bodyBytes, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}

	if httpResp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("local model returned status %d: %s", httpResp.StatusCode, string(bodyBytes))
	}

	var chatResp chatCompletionResponse
	if err := json.Unmarshal(bodyBytes, &chatResp); err != nil {
		return "", fmt.Errorf("failed to parse local model response: %w", err)
	}

	if chatResp.Error != nil && chatResp.Error.Message != "" {
		return "", fmt.Errorf("local model error: %s", chatResp.Error.Message)
	}

	if len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("no response generated by local model")
	}

	description := strings.TrimSpace(chatResp.Choices[0].Message.Content)
	return appendShippingInfo(description), nil
}
